MailMeBilling/Models/Vendorpayment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MailMeBilling.Models
{
    public class Vendorpayment
    {
        [Key]
        public int id { get; set; }
        public int billid { get; set; }
        public string name { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string paymenttype { get; set; }
        public string refno { get; set; }
        public decimal Payment { get; set; }
        public decimal total { get; set; }
        public decimal Balance { get; set; }
        public DateTime Paiddate { get; set; }
        public string Recivedby { get; set; }
        public string Branch { get; set; }
    }
}

MailMeBilling/Controllers/MyReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MailMeBilling.Data;
using MailMeBilling.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TimeZoneConverter;

namespace MailMeBilling.Controllers
{
    public class MyReportsController : Controller
    {
        private readonly ApplicationDbContext _context;
      
        public MyReportsController(ApplicationDbContext context)
        {
            _context = context;
        }


        public IActionResult Updatebill(SDateupdateVM sdate)
        {
            var billid = sdate.Billid;

            var bill = _context.salesinvoicesummery.Where(i => i.Billid == sdate.Billid).FirstOrDefault();
            bill.Billdate = sdate.BillDate;
            _context.salesinvoicesummery.Update(bill);

            var billhis = _context.customerpaymenthistry.Where(i => i.billid == sdate.Billid).FirstOrDefault();
            billhis.Paiddate = sdate.BillDate;
            _context.customerpaymenthistry.Update(billhis);




            _context.SaveChanges();

           
            return Redirect("/MyReports/Print/" + billid);

        }






        public IActionResult Salesreport()
        {
           
         
              ViewBag.branch = HttpContext.Session.GetObject(SD.Statusbranch);
          
            string Branch = ViewBag.branch;
            var sr = _context.salesinvoicesummery.Where(i => i.Branch == Branch && i.status !="Return" ).ToList();
            return View(sr);
        }
        public IActionResult Purchasereport()
        {
            ViewBag.branch = HttpContext.Session.GetObject(SD.Statusbranch);

            string Branch = ViewBag.branch;

            var sr = _context.purchaseinvoicesummeries.Where(i => i.status !="Return" && i.Branch == Branch).ToList();
            return View(sr);
        }

        public IActionResult Customerpayment(string id)
        {
          
            var list = _context.customerdetails.Where(i => i.Mobilenumber == id).FirstOrDefault();
            var bill = _context.salesinvoicesummery.Where(i => i.Mobilenumber == id).ToList();
            ViewBag.billsummery = bill;
            var histry = _context.customerpaymenthistry.Where(i => i.Mobile == id).ToList();
            ViewBag.histry = histry;


            return View(list);
        }
        public IActionResult Updatepayments(Customerpaymenthistry cph)
        {
          
             ViewBag.data = HttpContext.Session.GetObject(SD.Sessionname);
            var Name = ViewBag.data;
           // cph.Paiddate =  DateTime.UtcNow;
            cph.Recivedby = Name;
              ViewBag.branch = HttpContext.Session.GetObject(SD.Statusbranch);
            var Branch = ViewBag.branch;
            cph.Branch = Branch;

          
            var billamount = _context.salesinvoicesummery.Where(i => i.Billid == cph.billid).FirstOrDefault();
           decimal paid = cph.Payment;
            decimal cal = billamount.Balance - paid;
            decimal calamt = billamount.Paid + paid;
            billamount.Balance = cal;
            billamount.Paid = calamt;
            cph.total = billamount.Totalamount;

            if (cal == 0)
            {
                billamount.status = "Close";
            }
            var billhis = _context.customerpaymenthistry.Add(cph);
            _context.salesinvoicesummery.Update(billamount);
            _context.SaveChanges();



            return Json(new { success = true, message = "Save successfull." });
        }

        public IActionResult Vendorpayment(string id)
        {
           
            var list = _context.vendor.Where(i => i.Mobilenumber == id).FirstOrDefault();
            var bill = _context.purchaseinvoicesummeries.Where(i => i.Mobilenumber == id).ToList();
            ViewBag.billsummery = bill;
            var histry = _context.vendorpayments.Where(i => i.Mobile == id).ToList();
            ViewBag.histry = histry;


            return View(list);
        }
        public IActionResult Updatevendorpayments(Vendorpayment cph)
        {
          
             ViewBag.data = HttpContext.Session.GetObject(SD.Sessionname);
            var Name = ViewBag.data;
            //cph.Paiddate =  DateTime.UtcNow;
            cph.Recivedby = Name;
              ViewBag.branch = HttpContext.Session.GetObject(SD.Statusbranch);
            var Branch = ViewBag.branch;
            cph.Branch = Branch;

            var billhis = _context.vendorpayments.Add(cph);
            var billamount = _context.purchaseinvoicesummeries.Where(i => i.Billid == cph.billid).FirstOrDefault();
            decimal paid = cph.Payment;
            decimal cal = billamount.Balance - paid;
            billamount.Balance = cal;

            decimal calamt = billamount.paid + paid;
           
            billamount.paid = calamt;
            if (cal == 0)
            {
                billamount.status = "Close";
            }
            _context.purchaseinvoicesummeries.Update(billamount);
            Creditpaymenthistry cph1 = new Creditpaymenthistry();
            cph1.Mobile = cph.Mobile;
            cph1.Customername = cph.name;
            cph1.Address = cph.Address;
            cph1.paymenttype = cph.paymenttype;
            cph1.Payment = cph.Balance;
            cph1.Recivedby = Name;
            cph1.Paiddate = DateTime.UtcNow;
            cph1.Balance = cph.Balance;
            cph1.refno = cph.refno;
            cph1.Branch = Branch;
            cph1.total = cph.total;
            cph1.billid = cph.billid;
            _context.creditpaymenthistries.Add(cph1);

            _context.SaveChanges();



            return Json(new { success = true, message = "Save successfull." });
        }

        [HttpGet]
        public FileResult Viewbill(int id)
        {
            ViewBag.branch = HttpContext.Session.GetObject(SD.Statusbranch);
            var Branch = ViewBag.branch;

            var file = _context.purchaseinvoicesummeries.Where(i => i.Billid == id ).FirstOrDefault();



            return File(file.upload, "application/pdf");

        }



        public IActionResult print(int id)
        {
              ViewBag.branch = HttpContext.Session.GetObject(SD.Statusbranch);
          
            string Branch = ViewBag.branch;
            loadtemp load = new loadtemp();
            ViewBag.Branch = _context.branch.Where(i => i.Branchname == Branch).FirstOrDefault();
            var billno = _context.salesinvoicesummery.Where(i => i.Billid == id).FirstOrDefault(); //bill No         

            
            if (billno != null)
            {               
               
                var tmpsale = _context.salesinvoices.Where(i => i.Branch == Branch && i.Billno == id).ToList();
               
                    foreach (var item in tmpsale)
                    {

                        load.salesinvoices.Add(item);
                    }
                    var tmpsummery = _context.salesinvoicesummery.Where(i => i.Billid == id && i.Branch == Branch).ToList();
                   

                        foreach (var item in tmpsummery)
                        {
                    
                    TimeZoneInfo timeZone = TZConvert.GetTimeZoneInfo("India Standard Time");
                    var isdate = TimeZoneInfo.ConvertTime(item.Billdate, timeZone);
                    ViewBag.billdate = isdate;
                    load.salesinvoicesummeries.Add(item);
                        }
                  






            }
            return View(load);
        }

        public IActionResult printsr(int id)
        {

            
              ViewBag.branch = HttpContext.Session.GetObject(SD.Statusbranch);
         
            string Branch = ViewBag.branch;
            loadtemp load = new loadtemp();

            ViewBag.Branch = _context.branch.Where(i => i.Branchname == Branch).FirstOrDefault();
            var billno = _context.salesinvoicesummery.Where(i => i.Billid == id && i.Branch == Branch).FirstOrDefault(); //bill No         


            if (billno != null)
            {

                var tmpsale = _context.salesinvoices.Where(i => i.Branch == Branch && i.Billno == id).ToList();

                foreach (var item in tmpsale)
                {

                    load.salesinvoices.Add(item);
                }
                var tmpsummery = _context.salesinvoicesummery.Where(i => i.Billid == id && i.Branch == Branch).ToList();


                foreach (var item in tmpsummery)
                {

                    TimeZoneInfo timeZone = TZConvert.GetTimeZoneInfo("India Standard Time");
                    var isdate = TimeZoneInfo.ConvertTime(item.Billdate, timeZone);
                    ViewBag.billdate = isdate;
                    load.salesinvoicesummeries.Add(item);
                }







            }
            return View(load);
        }


        public IActionResult Salesreturnreport()
        {
           
              ViewBag.branch = HttpContext.Session.GetObject(SD.Statusbranch);
            string Branch = ViewBag.branch;
            var sr = _context.salesinvoicesummery.Where(i => i.status == "Return" && i.Branch == Branch).ToList();
            return View(sr);
        }
     
        public IActionResult Salesreturnbill(int id)
        {

          
          
              ViewBag.branch = HttpContext.Session.GetObject(SD.Statusbranch);
          ;
            string Branch = ViewBag.branch;
            loadtemp load = new loadtemp();


            //for print
            if (id != 0)
            {
              
                var tmp = _context.tmpsalesreturns.Where(i => i.Branch == Branch && i.Billno == id).ToList();
                var tmpsale = _context.salesinvoices.Where(i => i.Branch == Branch && i.Billno == id).ToList();
                if (tmpsale.Count != 0)               
                {

                    if (tmp != null)
                    {

MailMeBilling/Views/MyReports/Expense.cshtml
@model IEnumerable<MailMeBilling.Models.Expens>
@{
    ViewData["Title"] = "EXPENSE";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    int count = 0;
    decimal totalcredit = 0;
   
    decimal totalbalance = 0;
}

    <link href="~/css/PrintStyle.css" rel="stylesheet" />
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

<!-- ============ Main content start ============= -->
<div class="main-content" id="main">


    <div class="row" id="loadpage">
        <div class="col-md-12">
            <ul class="nav nav-tabs justify-content-end mb-4" id="myTab" role="tablist">

                <li class="nav-item"><a class="nav-link active" id="invoice-tab" data-toggle="tab" href="#invoice" role="tab" aria-controls="invoice" aria-selected="true">Statement</a></li>

            </ul>
            <div class="card">
                <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade show active " id="invoice" role="tabpanel" aria-labelledby="invoice-tab">

                        <form method="get" asp-action="customsalesreport">
                            <div class="row">
                                <div class="col-4">
                                    <b> FROM DATE:</b><span> <input type="date" name="fromdate" /></span>
                                </div>

                                <div class="col-3">
                                    <b> TO DATE:</b><span> <input type="date" name="todate" /></span>
                                </div>
                                <div class="col-5" style="text-align:left;">
                                    <input type="submit" value="Show" class="btn btn-success" />
                                </div>
                            </div>

                        </form>
                        <div class="d-sm-flex mb-5" data-view="print" id="printb" style="padding-right:30px;padding-bottom:150px;">
                            <span class="m-auto"></span>
                            <button class="btn btn-primary mb-sm-0 mb-3 print-invoice">Print Statement</button>
                        </div>

                        <div id="print-area" style="font-family:'Courier New';font-size:medium;padding-top:0px;margin-top:-100px;">
                            <div class="row">
                                <!-- -===== Print Area =======-->
                                <div class="col-12 text-center">


                                    <h1><b> Expense STATEMENT</b></h1>



                                    <table style="width:100%">

                                        <thead>
                                            <tr class="text-center" style="border: 1px solid black;font-family: Apple Chancery">
                                                <th style="padding-left: 10px; padding-right: 0px;  width: 1%;">S.No</th>
                                                <th style=" width: 20%;">DATE</th>
                                                <th style="width: 20%; text-align: center">REASON</th>

                                                <th style="width: 20%;text-align: center" ">ENTRY BY</th>
                                                <th style="width: 30%;text-align: right;padding-right: 80px;">AMOUNT</th>

                                            </tr>
                                        </thead>
                                        @foreach (var item in Model)
                                        {
                                            count++;
                                           

                                            string datein = Convert.ToDateTime(item.entrydate).ToString("dd/MM/yyyy");





                                            <tr class="text-center">
                                                <th>@count</th>
                                                <th>@datein</th>
                                                <th style="text-align: center">@item.reason</th>
                                                <th style="text-align: center">@item.entryby</th>
                                            
                                              
                                             

                                                <th style="text-align:right;padding-right:50px">@item.amount</th>
                                            </tr>

                                        }
                                        <tbody>
                                        </tbody>

                                        <tfoot>

                                            <tr style="text-align:right; border: 1px solid black; border-bottom-color:white; border-right-color:white; border-left-color:white; ">
                                                @{ var todebi = totalcredit + totalbalance;
                                                    var sumamt = Convert.ToDecimal(ViewBag.sumofcustomerbuyamount);
                                                    var balance = Convert.ToDecimal(sumamt) - Convert.ToDecimal(totalcredit);}
                                                <th colspan="5" style="text-align:right;padding-right:50px"><h4><b> @ViewBag.sumofcustomerbuyamount </b> </h4></th>
                                               
                                            </tr>
                                        

                                          
                                        </tfoot>
                                    </table>



                                </div>


                            </div>



                            <!-- ==== / Print Area =====-->
                        </div>
                        <div class="tab-pane fade show active" id="edit" role="tabpanel" aria-labelledby="edit-tab">
                            <!-- ==== Edit Area =====-->

                            <div class="mt-3 mb-4 border-top"></div>
                            <!-- ==== Entry Form Area =====-->
                            <!-- ==<== Entry Form Area End =====-->
                            <!-- ==== Form Area =====-->


                        </div>

                        <!-- ==== / Form Area =====-->
                        <!-- ==== / Edit Area =====-->
                    </div>
                </div>
            </div>
        </div>
    </div><!-- end of main-content -->
    <!-- Footer Start -->
</div>
<!-- ============ Main content End ============= -->

MailMeBilling/Views/MyReports/Purshasestatement.cshtml
@model IEnumerable<MailMeBilling.Models.Vendor>

@{
    ViewData["Title"] = "PURSHASE STATEMENT";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    int counter = 0;
}
<div class="card text-left">
    <div class="card-body">
        <div class="row">
            <div class="col-12">
                <h4 class="card-title mb-3"><b>Vendor Statement</b></h4>
                <p>All Branch Venor detail list here..</p>
            </div>

        </div>


        <div class="table-responsive">
            <table class="display table table-striped table-bordered" id="zero_configuration_table" style="width:100%">
                <thead>
                    <tr class="text-center">
                        <th>S.No</th>
                        <th>NAME</th>
                        <th>MOBILE NUMBAER</th>
                        <th>ADDRESS</th>
                        <th>ACTION</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        counter++;
                        <tr class="text-center">
                            <td> @counter</td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Mobilenumber)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item.Address)
                            </td>

                            <td>
                                <a class="btn btn-primary" asp-action="viewvendorstatement" asp-route-Mobnumber="@item.Mobilenumber">View Statement</a>

                            </td>
                        </tr>
                    }
                </tbody>

            </table>
        </div>


    </div>
</div>

MailMeBilling/Views/MyReports/Salesreturnreport.cshtml
@model IEnumerable<MailMeBilling.Models.Salesinvoicesummery>
@{
    ViewData["Title"] = "SALES RETURN REPORT";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}




<div class="card text-left">
    <div class="card-body">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="card-title mb-3"><b>SALES RETURN</b></h2>

            </div>

        </div>
        <div class="table-responsive">
            <table id="example" class="display table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr class="text-center">
                        <th>Bill No</th>
                        <th>Customer Name</th>
                        <th>Mobil Number</th>
                        <th>Balance</th>
                        <th>Status</th>
                        <th>Amount</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td class="text-center">@item.Billid</td>
                            <td class="text-center">@item.Customername</td>
                            <td class="text-center">@item.Mobilenumber</td>
                            <td class="text-right">@item.Balance</td>
                            <td class="text-center">
                                @if (@item.status == "Close")
                                {
                                    <span class="badge badge-success">Payment @item.status</span>
                                }
                                else
                                {
                                    <span class="badge badge-warning">Payment @item.status</span>
                                }


                            </td>
                            <td class="text-right">@item.Totalamount</td>
                            <td class="text-center">

                              @*<a asp-controller="MyReports" asp-action="Salesreturnbill" asp-route-id="@item.Billid" class="btn btn-primary">Return</a>*@
                                <a asp-controller="MyReports" asp-action="printsr" asp-route-id="@item.Billid" class="btn btn-primary" target="_blank">Print</a>




                            </td>



                        </tr>
                    }

                </tbody>
                <tfoot>
                    <tr>
                        <th colspan="6" style="text-align:right">Total:</th>
                        <th></th>
                    </tr>
                </tfoot>
            </table>
        </div>

    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.js"
        integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
        crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>


<script>

    $(document).ready(function () {
        $('#example').DataTable({
            "footerCallback": function (row, data, start, end, display) {
                var api = this.api(), data;

                // Remove the formatting to get integer data for summation
                var intVal = function (i) {
                    return typeof i === 'string' ?
                        i.replace(/[\₹,]/g, '') * 1 :
                        typeof i === 'number' ?
                            i : 0;
                };

                // Total over all pages
                total = api
                    .column(5)
                    .data()
                    .reduce(function (a, b) {
                        return intVal(a) + intVal(b);
                    }, 0);

                // Total over this page
                pageTotal = api
                    .column(5, { page: 'current' })
                    .data()
                    .reduce(function (a, b) {
                        return intVal(a) + intVal(b);
                    }, 0);

                // Update footer
                $(api.column(5).footer()).html(
                    '₹' + pageTotal + ' ( ₹' + total + ' total)'
                );
            }
        });
    });

</script>

MailMeBilling/Views/MyReports/Salestatement.cshtml
@model IEnumerable<MailMeBilling.Models.CustomerDetails>

@{
    ViewData["Title"] = "CUSTOMER STATEMENT";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    int counter = 0;
}
<div class="card text-left">
    <div class="card-body">
        <div class="row">
            <div class="col-12">
                <h4 class="card-title mb-3"><b>Customer Statement</b></h4>
                <p>All Branch Customer detail list here..</p>
            </div>
           
        </div>


        <div class="table-responsive">
            <table class="display table table-striped table-bordered" id="zero_configuration_table" style="width:100%">
                <thead>
                    <tr class="text-center">
                        <th>S.No</th>
                        <th>NAME</th>
                        <th>MOBILE NUMBAER</th>
                        <th>ADDRESS</th>
                        <th>ACTION</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        counter++;
                        <tr class="text-center">
                            <td> @counter</td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Customername)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Mobilenumber)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item.Address)
                            </td>

                            <td>
                                <a class="btn btn-primary" asp-action="viewcustomerstatement" asp-route-Mobnumber="@item.Mobilenumber">View Statement</a>
                                
                            </td>
                        </tr>
                    }
                </tbody>

            </table>
        </div>


    </div>
</div>

MailMeBilling/Views/MyReports/print.cshtml
@model MailMeBilling.Models.loadtemp
@{
    ViewData["Title"] = "SALES REPORT BILL";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";



}
    <style>
        table, th, td {
            border: 1px solid black;
        }
    </style>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

<!-- ============ Main content start ============= -->
<div class="main-content" id="main">


    <div class="row" id="loadpage">
        <div class="col-md-12">
            <ul class="nav nav-tabs justify-content-end mb-4" id="myTab" role="tablist">
                @*<li class="nav-item"><a class="nav-link " id="edit-tab" data-toggle="tab" href="#edit" role="tab" aria-controls="edit" aria-selected="false">Billing</a></li>*@
                <li class="nav-item"><a class="nav-link active" id="invoice-tab" data-toggle="tab" href="#invoice" role="tab" aria-controls="invoice" aria-selected="true">Copy Bill</a></li>

            </ul>
            <div class="card">
                <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade show active " id="invoice" role="tabpanel" aria-labelledby="invoice-tab">

                        <!-- -===== Print Area =======-->


                        <div class="d-sm-flex mb-5" data-view="print" id="printb" style="padding-bottom:150px;">
                            <span class="m-auto"></span>
                            <button class="btn btn-primary mb-sm-0 mb-3 print-invoice">Print Invoice</button>
                            <br/>
                            <!-- Button trigger modal -->
                           <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                               Change Bill Date
                            </button>
                           
                            <!-- Modal -->
                            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Update Bill Date</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <form method="post" asp-controller="MyReports" asp-action="Updatebill">
                                            <div class="modal-body">

                                                <div class="form-group">
                                                    <label for="recipient-name" class="col-form-label">Date:</label>
                                                    @foreach (var sums in Model.salesinvoicesummeries)
                                                    {
                                                        <input type="hidden" value="@sums.Billid" name="Billid" />
                                                        <input type="datetime-local" class="form-control" name="BillDate" id="recipient-name" required>
                                                    }
                                                </div>

                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                <button type="submit" class="btn btn-primary">Save changes</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <partial name="printsections" />
                       
                        <!-- ==== / Print Area =====-->
                    </div>
                    <div class="tab-pane fade show active" id="edit" role="tabpanel" aria-labelledby="edit-tab">
                        <!-- ==== Edit Area =====-->
                        
                        <div class="mt-3 mb-4 border-top"></div>
                        <!-- ==== Entry Form Area =====-->
                      
                        <!-- ==<== Entry Form Area End =====-->
                        <!-- ==== Form Area =====-->
                        

                    </div>

                    <!-- ==== / Form Area =====-->
                    <!-- ==== / Edit Area =====-->
                </div>
            </div>
        </div>
    </div>
</div><!-- end of main-content -->
<!-- Footer Start -->
<!-- ============ Main content End ============= -->