MailMeBilling/Controllers/EmiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MailMeBilling.Data;
using MailMeBilling.Models;
using Microsoft.AspNetCore.Http;

namespace MailMeBilling.Controllers
{
    public class EmiController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EmiController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: creditnotes
        public async Task<IActionResult> Index()
        {
           
            return View(await _context.creditnote.ToListAsync());
        }
        public async Task<IActionResult> CustomerIndex()
        {
            
            return View(await _context.eminotes.Where(i => i.person == "customer").ToListAsync());
        }

        public async Task<IActionResult> VendorIndex()
        {
          
            return View(await _context.eminotes.Where(i => i.person == "vendor").ToListAsync());
        }

        // GET: creditnotes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
           
            if (id == null)
            {
                return NotFound();
            }

            var creditnote = await _context.eminotes
                .FirstOrDefaultAsync(m => m.cid == id);
            if (creditnote == null)
            {
                return NotFound();
            }

            return View(creditnote);
        }

        // GET: creditnotes/Create
        public IActionResult AddEmi()
        {
           
            return View();
        }

        // POST: creditnotes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("cid,cdate,balance,paid,person,particular,totalamount,name,mobilenumber,address,paymenttype,refno")] Eminote creditnote)
        {
           
         
            if (ModelState.IsValid)
            {
                 ViewBag.data = HttpContext.Session.GetObject(SD.Sessionname);
                var Name = ViewBag.data;              
                  ViewBag.branch = HttpContext.Session.GetObject(SD.Statusbranch);
                string Branch = ViewBag.branch;
                creditnote.addby = Name;
                creditnote.branch = Branch;
                if (creditnote.cdate == null)
                {
                    creditnote.cdate = DateTime.UtcNow;
                }
              
                _context.eminotes.Add(creditnote);
                await _context.SaveChangesAsync();
                var cno = creditnote.cid;
                if (creditnote.person =="customer")
                {
                    var checkcustomer = _context.creditcustomers.Where(i => i.Mobilenumber == creditnote.mobilenumber).FirstOrDefault();
                    if (checkcustomer == null)
                    {
                        CreditCustomerDetails cd = new CreditCustomerDetails();
                        cd.Mobilenumber = creditnote.mobilenumber;
                        cd.Customername = creditnote.name;
                        cd.Address = creditnote.address;
                        cd.Branch = Branch;
                        cd.Entrydate = DateTime.UtcNow;
                        cd.Entryby = Name;
                        _context.creditcustomers.Add(cd);
                        _context.SaveChanges();

                    }
                        Emipaymenthistry cph1 = new Emipaymenthistry();
                        cph1.Mobile = creditnote.mobilenumber;
                        cph1.Customername = creditnote.name;
                        cph1.Address = creditnote.address;
                        cph1.paymenttype = creditnote.paymenttype;
                        cph1.Payment = creditnote.paid;
                        cph1.Recivedby = Name;
                        if (creditnote.cdate == null)
                        {
                            cph1.Paiddate = DateTime.UtcNow;
                        }
                        cph1.Paiddate = creditnote.cdate;
                        cph1.Balance = creditnote.balance;
                       
                        cph1.refno = creditnote.refno;
                        cph1.Branch = Branch;
                        cph1.total = creditnote.totalamount;
                      
                        cph1.billid = cno;
                        _context.emipaymenthistries.Add(cph1);

                     
                        _context.SaveChanges();
                    

                }

                if (creditnote.person == "vendor")
                {
                    var checkvendor = _context.creditvendors.Where(i => i.Mobilenumber == creditnote.mobilenumber).FirstOrDefault();
                    if (checkvendor == null)
                    {
                        CreditVendor cd = new CreditVendor();
                        cd.Mobilenumber = creditnote.mobilenumber;
                        cd.Name = creditnote.name;
                        cd.Address = creditnote.address;
                        cd.Branch = Branch;
                        cd.Entrydate = DateTime.UtcNow;
                        cd.Entryby = Name;
                        _context.creditvendors.Add(cd);
                        _context.SaveChanges();
                    }
                    Emipaymenthistry cph1 = new Emipaymenthistry();
                    cph1.Mobile = creditnote.mobilenumber;
                    cph1.Customername = creditnote.name;
                    cph1.Address = creditnote.address;
                    cph1.paymenttype = creditnote.paymenttype;
                    cph1.Payment = creditnote.paid;
                    cph1.Recivedby = Name;
                    if (creditnote.cdate == null)
                    {
                        cph1.Paiddate = DateTime.UtcNow;
                    }
                    cph1.Paiddate = creditnote.cdate;
                    cph1.Balance = creditnote.balance;

                    cph1.refno = creditnote.refno;
                    cph1.Branch = Branch;
                    cph1.total = creditnote.totalamount;

                    cph1.billid = cno;
                    _context.emipaymenthistries.Add(cph1);

                    _context.SaveChanges();
                }

                if (creditnote.person == "vendor")
                {
                    return RedirectToAction(nameof(VendorIndex));
                }
                else
                {
                    return RedirectToAction(nameof(CustomerIndex));
                }
            }
            return View();
        }

        // GET: creditnotes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
           
            if (id == null)
            {
                return NotFound();
            }

            var creditnote = await _context.creditnote.FindAsync(id);
            if (creditnote == null)
            {
                return NotFound();
            }
            return View(creditnote);
        }

        // POST: creditnotes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("cid,cdate,person,particular,totalamount,name,mobilenumber,address")] creditnote creditnote)
        {
           
            if (id != creditnote.cid)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    creditnote.cdate = DateTime.UtcNow;
                    _context.Update(creditnote);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!creditnoteExists(creditnote.cid))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return View();
            }
            return View(creditnote);
        }

        // GET: creditnotes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
          
            if (id == null)
            {
                return NotFound();
            }

            var creditnote = await _context.eminotes
                .FirstOrDefaultAsync(m => m.cid == id);
            if (creditnote == null)
            {
                return NotFound();
            }

            return View(creditnote);
        }

        // POST: creditnotes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var creditnote = await _context.eminotes.FindAsync(id);
            _context.eminotes.Remove(creditnote);
            var role = creditnote.person;
            await _context.SaveChangesAsync();
            if (role == "vendor")
            {
                return RedirectToAction(nameof(VendorIndex));
            }
            else
            {
                return RedirectToAction(nameof(CustomerIndex));
            }
          
        }

        private bool creditnoteExists(int id)
        {
            return _context.creditnote.Any(e => e.cid == id);
        }
        [HttpGet]
        public JsonResult fillcusdetails(string mob)
        {
          

MailMeBilling/Views/Emi/AddEmi.cshtml
@model MailMeBilling.Models.Eminote

@{
    ViewData["Title"] = "ADD CREDIT";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}



<h4>Add Credit Note</h4>
<hr />


<form asp-action="Create">
    <div class="row">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="col-md-6">
            <div class="form-group">
                <label asp-for="mobilenumber" class="control-label"></label>
                <input asp-for="mobilenumber" id="cnumber" class="form-control" onchange="checkcustomer()" value="" required />
                <span asp-validation-for="mobilenumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" id="name" class="form-control" required />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="address" class="control-label"></label>

                <textarea asp-for="address" id="address" class="form-control" required>

                    </textarea>
                <span asp-validation-for="address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="paymenttype" class="control-label"></label>

                <select asp-for="paymenttype" class="form-control" required>
                    <option value="">Select Payment Type</option>
                    <option value="Card">Card</option>
                    <option value="Cash">Cash</option>
                    <option value="Netpay">Net Pay</option>
                    <option value="Upi">UPI</option>
                    <option value="Credit">Credit</option>
                </select>
                <span asp-validation-for="paymenttype" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="refno" class="control-label"></label>
                <input asp-for="refno" id="ref" class="form-control" />
                <span asp-validation-for="refno" class="text-danger"></span>
            </div>

        </div>
        <div class="col-md-6">

            <div class="form-group">
                <label asp-for="person" class="control-label"></label>

                <select asp-for="person" class="form-control" required>
                    <option value="">Select</option>
                    <option value="customer">Customer</option>
                    <option value="vendor">Vendor</option>
                </select>
                <span asp-validation-for="person" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="particular" class="control-label"></label>
                <input asp-for="particular" class="form-control" required />
                <span asp-validation-for="particular" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="totalamount" class="control-label"></label>
                <input asp-for="totalamount" id="totalamount" class="form-control" required />
                <span asp-validation-for="totalamount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="paid" class="control-label"></label>
                <input asp-for="paid" class="form-control" onkeyup="balancecal(this)" autocomplete="off" required />
                <span asp-validation-for="paid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="balance" class="control-label"></label>
                <input asp-for="balance" id="balance" class="form-control" required readonly />
                <span asp-validation-for="balance" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="cdate" class="control-label"></label>
                <input asp-for="cdate" class="form-control" required />
                <span asp-validation-for="cdate" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" id="Save" class="btn btn-primary" />
            </div>
        </div>

    </div>
</form>





<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script>


    function balancecal(amt) {
        var amount = amt;
        var togst = document.getElementById("totalamount");
        var res = document.getElementById("balance");

        var tmp = parseFloat(togst.value) - parseFloat(amount.value)
        console.log(tmp);
        if (isNaN(tmp)) {
            res.value = 0;
        }
        else {
            res.value = tmp;
        }

    }
     function checkcustomer() {

         var num = $('#cnumber').val();
        $.ajax({
            url: '@Url.Action("fillcusdetails")',
            type: "GET",
            dataType: "JSON",
            data: { mob: num },
            success: function (data) {

                if (data != null) {
                    $("#Save").prop("disabled", false);
                    var Cat = document.getElementById("name");
                    var sub = document.getElementById("address");
                    $(Cat).empty();
                    Cat.value = data['customername'];
                    if (Cat.value == "undefined")
                    {
                        Cat.value = data['name'];
                    } else
                    {
                        Cat.value = data['customername'];

                    }

                    sub.value = data['address'];


                    toastr.success("This Customer Already Registered", "Our  Client", {
                        closeButton: !0
                    });
                }
                else {
                    toastr.success("This Client is new", "New  Client", {
                        closeButton: !0
                    });

                }





            }

        });

    }
</script>

MailMeBilling/Views/Emi/Creditcustomerstatement.cshtml
@model IEnumerable<MailMeBilling.Models.CreditCustomerDetails>

@{
    ViewData["Title"] = "CUSTOMER CREDIT STATEMENT";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    int counter = 0;
}
<div class="card text-left">
    <div class="card-body">
        <div class="row">
            <div class="col-12">
                <h4 class="card-title mb-3"><b>Credit Customer Statement</b></h4>
                <p>All Branch Customer detail list here..</p>
            </div>

        </div>


        <div class="table-responsive">
            <table class="display table table-striped table-bordered" id="zero_configuration_table" style="width:100%">
                <thead>
                    <tr class="text-center">
                        <th>S.No</th>
                        <th>NAME</th>
                        <th>MOBILE NUMBAER</th>
                        <th>ADDRESS</th>
                        <th>ACTION</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        counter++;
                        <tr class="text-center">
                            <td> @counter</td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Customername)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Mobilenumber)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item.Address)
                            </td>

                            <td>
                                <a class="btn btn-primary" asp-action="viewcustomerstatement" asp-route-Mobnumber="@item.Mobilenumber">View Statement</a>

                            </td>
                        </tr>
                    }
                </tbody>

            </table>
        </div>


    </div>
</div>

MailMeBilling/Views/Emi/Creditvendorstatement.cshtml
@model IEnumerable<MailMeBilling.Models.CreditVendor>

@{
    ViewData["Title"] = "PURSHASE STATEMENT";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    int counter = 0;
}
<div class="card text-left">
    <div class="card-body">
        <div class="row">
            <div class="col-12">
                <h4 class="card-title mb-3"><b>Vendor Statement</b></h4>
                <p>All Branch Venor detail list here..</p>
            </div>

        </div>


        <div class="table-responsive">
            <table class="display table table-striped table-bordered" id="zero_configuration_table" style="width:100%">
                <thead>
                    <tr class="text-center">
                        <th>S.No</th>
                        <th>NAME</th>
                        <th>MOBILE NUMBAER</th>
                        <th>ADDRESS</th>
                        <th>ACTION</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        counter++;
                        <tr class="text-center">
                            <td> @counter</td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Mobilenumber)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item.Address)
                            </td>

                            <td>
                                <a class="btn btn-primary" asp-action="viewvendorstatement" asp-route-Mobnumber="@item.Mobilenumber">View Statement</a>

                            </td>
                        </tr>
                    }
                </tbody>

            </table>
        </div>


    </div>
</div>

MailMeBilling/Views/Emi/CustomerIndex.cshtml
@model IEnumerable<MailMeBilling.Models.Eminote>

@{
    ViewData["Title"] = "CUSTOMER CREDIT LIST";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    int con = 0;
}



<div class="card text-left">
    <div class="card-body">
        <div class="row">
            <div class="col-10">
                <h4 class="card-title mb-3"><b> A/C Note</b></h4>
                <p>Customer A/C Note List</p>
            </div>
            <div class="col-2">
                <p class="text-right">
                    <a asp-action="AddEmi" class="btn btn-primary">Add A/C Note</a>
                </p>
            </div>
        </div>


        <div class="table-responsive">
            <table class="display table table-striped table-bordered" id="zero_configuration_table" style="width:100%">
                <thead>
                    <tr>
                        <th>
                            Bill.No
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.cdate)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.person)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.particular)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.paymenttype)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.refno)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.totalamount)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.mobilenumber)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.address)
                        </th>
                        <th style="width:70px;">Action</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var item in Model)
                    {
                        con++;
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.cid)
                            </td>
                            <td style="width:100px">
                                @Html.DisplayFor(modelItem => item.cdate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.person)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.particular)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.paymenttype)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.refno)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item.totalamount)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.mobilenumber)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.address)
                            </td>
                            <td>
                                <a class=" nav-icon mr-2 i-Pen-2" asp-action="Creditnotepayment" asp-controller="Emi" asp-route-id="@item.cid" asp-route-mob="@item.mobilenumber"></a>
                                <a class="nav-icon mr-2 i-Information" asp-action="Details" asp-route-id="@item.cid"></a>
                                <a class="nav-icon mr-2 i-Close" asp-action="Delete" asp-route-id="@item.cid"></a>
                            </td>
                        </tr>
                    }
                </tbody>

            </table>
        </div>
    </div>
</div>

MailMeBilling/Views/Emi/Delete.cshtml
@model MailMeBilling.Models.Eminote

@{
    ViewData["Title"] = "DELETE CREDIT NOTE";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Credit Note</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.cdate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.cdate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.person)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.person)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.particular)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.particular)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.totalamount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.totalamount)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.mobilenumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.mobilenumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.address)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.address)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="cid" />
        <input type="submit" value="Delete" class="btn btn-danger" />

    </form>
</div>

MailMeBilling/Views/Emi/VendorIndex.cshtml
@model IEnumerable<MailMeBilling.Models.Eminote>

@{
    ViewData["Title"] = "VENDOR CREDIT LIST";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    int con = 0;
}




<div class="card text-left">
    <div class="card-body">
        <div class="row">
            <div class="col-10">
                <h4 class="card-title mb-3"><b> A/C Note</b></h4>
                <p>Vendor A/C Note List</p>
            </div>
            <div class="col-2">
                <p class="text-right">
                    <a asp-action="AddEmi" class="btn btn-primary">Add A/C Note</a>
                </p>
            </div>
        </div>


        <div class="table-responsive">
            <table class="display table table-striped table-bordered" id="zero_configuration_table" style="width:100%">
                <thead>
                    <tr>
                        <th>
                            Bill.No
                        </th>
                        <th style="width:100px">
                            @Html.DisplayNameFor(model => model.cdate)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.person)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.particular)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.paymenttype)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.refno)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.totalamount)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.mobilenumber)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.address)
                        </th>
                        <th style="width:70px">Action</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var item in Model)
                    {
                        con++;
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.cid)
                            </td>
                            <td style="width:100px">
                                @Html.DisplayFor(modelItem => item.cdate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.person)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.particular)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.paymenttype)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.refno)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item.totalamount)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.mobilenumber)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.address)
                            </td>
                            <td>
                                <a class=" nav-icon mr-2 i-Pen-2" asp-action="Creditnotepayment" asp-controller="Emi" asp-route-id="@item.cid" asp-route-mob="@item.mobilenumber"></a>
                                <a class="nav-icon mr-2 i-Information" asp-action="Details" asp-route-id="@item.cid"></a>
                                <a class="nav-icon mr-2 i-Close" asp-action="Delete" asp-route-id="@item.cid"></a>
                            </td>
                        </tr>
                    }
                </tbody>

            </table>
        </div>
    </div>
</div>